### ISSUE TITLE
Rename from qss (quantum systems software) to qe (quantum engine) - compiler

### ISSUE THREAD

**Issue by taalexander** [openqasm/qe-compiler#210]
As part of migrating to the open source we are renaming this project from the qss (quantum systems software) prefix to qe (quantum engine).

Steps:
- [x]  Point this repositories dependencies to the [migrated qss-qasm](https://github.com/Qiskit/qss-qasm/issues/23)
- [x] Point internal repositories dependencies to the [migrated qss-qasm](https://github.com/Qiskit/qss-qasm/issues/23)
- [x] Update internal repositories 
- [x] Rename the repository and migrate to the openqasm organization
- [ ] Migrate all code references from qss->qe and quantum systems software to quantum engine
- [x] Update [the readme](https://github.com/Qiskit/qss-compiler/pull/209)
    - [ ] Remove the repository name migration notice added in #209
- [ ] Update all internal production usages to migrate to the new name wherever used
- [ ] Update the internal repository to point to the updated references
