### ISSUE TITLE
Prepare the code to reuse other Payload generation implementation (pluggable library)

### ISSUE THREAD

**Issue by jgsogo** [openqasm/qe-compiler#31]
From the Quantum team we will be publishing a package with the QEM payload definition (schemas and serialization), so we can implement a [`Payload` class](https://github.com/Qiskit/qss-compiler/blob/main/include/Payload/Payload.h) that writes this format.

## Tasks

 - [ ] Consume library with the new QEM payload
 - [ ] Prepare source code to accept this pluggable implementation
 - [ ] Use new Payload class
 - [ ] Provide some flag (?) to activate this new output format in Python bindings
